# Generated by Django 3.0 on 2020-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=30)),
            ],
        ),
    ]
